Channel 1 support
CopterExpress/ros_led pull request #4
Opened 2021-10-11 07:14 UTC by siddharthcb

I have documented the errors and solutions for the issues encountered for using the channel 1 GPIOs. Hope this is helpful.

2021-10-18 22:05 UTC, okalachev requested changes
Hi, @siddharthcb! Thanks for your interest and contribution to the package!

But I see the following issues with your it:

1. Your idea, as I understood, is to create a separate branch for channel-1 support; but your pull request is created against the `master` branch of the repo, so no `channel-1` branch would not be created.

    Anyway, I don't find this idea optimal. It would be not convenient to have two separate branches supported, for just one little feature. Why instead just not to create and document a ROS parameter for this feature, if it's really useful?

2. You replaced the entire readme with other content, removing all the main information, which is not good. The main readme should stay.
3. Irrelevant changes, like removing `.gitignore`, changing file permissions, adding examples should be put away from this PR.
4. Adding something to `/etc/ld.so.conf` seems like a hack a bit, it would be great to find a better solution.

2021-10-18 22:05 UTC, okalachev commented on ws281x/examples/example.py
> +        return Color(pos * 3, 255 - pos * 3, 0)
This won't work anyway, `Color` is not defined.

2021-10-18 22:05 UTC, okalachev commented on ws281x/examples/example.py
> -fill_strip(0, 0, 0)
Please, don't change the example code as this is unrelated to the main change.

2021-10-18 22:05 UTC, okalachev commented on ws281x/srv/test.py
> +import rospy
What is the purpose of this file? Python script should not be in `srv` directory.

2021-10-18 22:05 UTC, okalachev commented on ws281x/vendor/rpi_ws281x/.gitignore
> -.sconsign.dblite
`.gitignore` should not be removed.

2021-10-18 22:05 UTC, okalachev commented on ws281x/vendor/rpi_ws281x/python/.gitignore
> -*.pyc
Should not be removed.

2021-10-20 08:55 UTC, siddharthcb commented
hello @okalachev ,
sorry for the confusion and I understand the changes to be made.
I will close this pull request for now and open a new one with optimal solution for channel 1.

2021-10-20 08:56 UTC, okalachev commented
@siddharthcb, remaking the pull request is not necessary. You can keep this PR and edit your `channel-1` branch.

2021-10-20 08:57 UTC, closed without merging